services:
  research-evaluator-agent-service:
    image: research_evaluator_agent:latest
    container_name: research-evaluator-agent
#    command: [ "bash /app/entrypoint.sh" ]
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8077:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8077/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    entrypoint: [ "/app/.venv/bin/uvicorn", "src.research_evaluator_agent.server.app:app", "--host", "0.0.0.0", "--port", "8000" ]
